'use strict';
const $=id=>document.getElementById(id);
const store={get(k){try{return localStorage.getItem(k)}catch{return null}},set(k,v){try{localStorage.setItem(k,v)}catch{}}};
let session;try{session=JSON.parse(sessionStorage.getItem('synchrony-session')||'null')}catch{session=null}
let state=null, eventId=-1, streamController=null, generation=0, connected=false, busy=false, playingCard=false, clockOffset=0, toastTimer, soundOn=store.get('synchrony-sound')==='true', audioContext;
let server=(window.SYNCHRONY_SERVER||store.get('synchrony-server')||(/^(localhost|127\.0\.0\.1)$/.test(location.hostname)?location.origin:'')).replace(/\/$/,'');
const hue=n=>145-((n-1)/Math.max(1,(state?.deck||100)-1))*145;
const escapeHTML=s=>String(s).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
function saveSession(){try{session?sessionStorage.setItem('synchrony-session',JSON.stringify(session)):sessionStorage.removeItem('synchrony-session')}catch{}}
function toast(text){clearTimeout(toastTimer);$('toast').textContent=text;$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,4500)}
function sound(type){if(!soundOn)return;try{audioContext ||= new (window.AudioContext||window.webkitAudioContext)();audioContext.resume();const notes=type==='mistake'||type==='lost'?[150,100]:type==='won'||type==='success'?[440,554,659,880]:type==='countdown'?[330]:[520];notes.forEach((f,i)=>{const o=audioContext.createOscillator(),g=audioContext.createGain(),t=audioContext.currentTime+i*.1;o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.06,t+.015);g.gain.exponentialRampToValueAtTime(.0001,t+.25);o.connect(g);g.connect(audioContext.destination);o.start(t);o.stop(t+.27)})}catch{}}
function setConnection(value){connected=value;$('connection').textContent=value?'Mentes conectadas':session?'Reconectando…':'Encuentra tu ritmo';$('connection').classList.toggle('online',value);if(state)renderControls()}
async function api(data,authenticated=true){if(!server)throw Error('Configura la dirección de Render en «Conexión al servidor».');const headers={'Content-Type':'application/json'};if(authenticated&&session){headers.Authorization='Bearer '+session.token;headers['X-Room-Code']=session.code}const response=await fetch(server+'/api',{method:'POST',headers,body:JSON.stringify(data),signal:AbortSignal.timeout(90000)});const result=await response.json();if(!response.ok)throw Error(result.error||'No se ha podido conectar.');return result}
function tab(name){document.querySelectorAll('[data-tab]').forEach(b=>{const active=b.dataset.tab===name;b.setAttribute('aria-selected',active);b.tabIndex=active?0:-1;$(b.dataset.tab+'-panel').hidden=!active});$('form-error').textContent=''}
document.querySelectorAll('[data-tab]').forEach(b=>{b.onclick=()=>tab(b.dataset.tab);b.onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const tabs=[...document.querySelectorAll('[data-tab]')],i=tabs.indexOf(b),next=tabs[(i+(e.key==='ArrowRight'?1:2))%3];tab(next.dataset.tab);next.focus()}}});
async function enter(action){if(busy)return;const name=$('name').value.trim();if(!name){$('name').focus();$('form-error').textContent='Escribe tu nombre para conectar.';return}busy=true;const button=$(action==='create'?'create-panel':action==='join'?'join-panel':'match-panel').querySelector('button');const original=button.innerHTML;button.disabled=true;button.textContent='Conectando…';$('form-error').textContent='';try{const data={action,name};if(action==='create'){data.players=Number($('players').value);data.deck=Number($('deck').value)}if(action==='join')data.code=$('code').value.trim();if(action==='match')data.players=Number($('online-players').value);const result=await api(data,false);store.set('synchrony-name',name);session={token:result.token,code:result.code,server};saveSession();eventId=-1;state=null;apply(result.state);openStream();}catch(e){$('form-error').textContent=e.name==='TimeoutError'?'El servidor tarda en despertar. Vuelve a intentarlo en unos segundos.':e.message==='Failed to fetch'?'No se pudo conectar. Comprueba la dirección del servidor y su configuración de origen.':e.message}finally{busy=false;button.disabled=false;button.innerHTML=original}}
['create','join','match'].forEach(action=>$(action+'-panel').onsubmit=e=>{e.preventDefault();enter(action)});
function apply(next){clockOffset=next.serverNow-Date.now();if(state&&next.revision<state.revision)return;const first=!state;const changed=first||next.revision!==state.revision;state=next;$('home').hidden=true;$('room').hidden=false;$('room-code').textContent=state.code;$('room-kind').textContent=state.public?'PARTIDA ONLINE':'SALA PRIVADA';if(!changed){updateClock();return}render();if(!first&&state.event.id!==eventId){animateEvent(state.event)}eventId=state.event.id;updateClock()}
function render(){const s=state,me=s.players.find(p=>p.id===s.me),active=s.players.filter(p=>!p.excluded);$('round-label').textContent=String(s.round).padStart(2,'0');$('lives').innerHTML='♥'.repeat(s.lives)+'<span class="dead-heart">'+'♥'.repeat(5-s.lives)+'</span>';$('lives').setAttribute('aria-label',`${s.lives} vidas`);$('player-count').textContent=s.phase==='lobby'?`${active.length} / ${s.capacity}`:`${active.length}`;
$('players-list').innerHTML=s.players.map((p,i)=>`<div class="player ${p.id===s.me?'is-me':''}"><div class="avatar" style="--avatar-hue:${(i*53+100)%360}">${escapeHTML(p.name.slice(0,2).toUpperCase())}</div><div class="player-info"><div class="player-name">${escapeHTML(p.name)}${p.id===s.me?' · tú':''}</div><div class="player-state ${p.ready?'ready-state':''}">${p.excluded?'Espectador':!p.online?'Reconectando · 30 s':p.ready?'Mente preparada':s.phase==='playing'?`${p.count} carta${p.count===1?'':'s'}`:'Esperando el latido'}</div></div><span class="player-badge">${p.ready?'✓':p.excluded?'—':s.phase==='playing'&&p.count===0?'✓':''}</span></div>`).join('');
const card=$('table-card');card.classList.toggle('empty',!s.last);card.style.setProperty('--hue',hue(s.last||1));card.innerHTML=`<span class="corner top">${s.last||'∞'}</span><strong style="font-size:${s.last?Math.min(57,190/String(s.last).length):57}px">${s.last||'◎'}</strong><span class="corner bottom">${s.last||'∞'}</span>`;
$('table-caption').textContent=s.phase==='playing'?'LA ÚLTIMA CARTA JUGADA':'EL CENTRO DE VUESTRA CONEXIÓN';$('table-note').textContent=s.event.text;
$('progress-label').textContent=s.phase==='lobby'?`${active.filter(p=>p.ready).length} mentes listas · ${Math.max(0,s.capacity-active.length)} por conectar`:`${s.played} / ${s.dealt} cartas jugadas${s.removed?' · '+s.removed+' retiradas':''}`;
$('deck-label').textContent=`Baraja ${s.deck} · Meta ${Math.ceil(s.deck*.79)}`;$('progress-bar').style.width=(s.dealt?100*(s.played+s.removed)/s.dealt:0)+'%';
$('hand-count').textContent=s.hand.length;$('hand-tip').textContent=me?.excluded?'Observas esta partida.':s.phase==='playing'?'Pulsa una carta cuando sientas que es su momento.':'Solo tú puedes ver estas cartas.';
$('hand').innerHTML=s.hand.length?s.hand.map((n,i)=>`<button type="button" class="hand-card" data-card="${n}" aria-label="Jugar carta ${n}" style="--hue:${hue(n)};--delay:${Math.min(i*25,300)}ms"><span class="corner top">${n}</span><b style="font-size:${Math.min(29,105/String(n).length)}px">${n}</b><span class="corner bottom">${n}</span></button>`).join(''):`<p class="empty-hand">${me?.excluded?'Tu equipo sigue jugando.':s.phase==='playing'?'Ya has jugado tus cartas. Confía en tu equipo.':['won','lost','abandoned'].includes(s.phase)?'Gracias por compartir vuestro ritmo.':'Las cartas llegarán cuando estéis todos listos.'}</p>`;
const text={lobby:['Conectando mentes…',`Esperando a ${s.capacity} jugadores. Todos debéis confirmar.`],countdown:['Un mismo latido.', 'Respirad. Vuestras cartas están a punto de llegar.'],playing:['Confía en tu intuición.', 'De menor a mayor. Sin turnos. Sin decir los números.'],between:['Ronda superada.',`Ahora recibiréis hasta ${s.round} cartas por persona. ¿Preparados?`],retry:['Un latido a destiempo.',`Repetimos la ronda ${s.round} con nuevas cartas. Os quedan ${s.lives} vidas.`],won:['Sincronía perfecta.',`Habéis jugado ${s.played} cartas: al menos el 79 % de la baraja.`],lost:['El silencio también enseña.', 'No quedan vidas. Un nuevo equipo, un nuevo intento.'],abandoned:['La conexión ha terminado.', 'Ya no quedan participantes en esta partida.']}[s.phase];
$('status-title').textContent=text[0];$('status-message').textContent=text[1];$('status-panel').className='status-panel'+(['retry','lost'].includes(s.phase)?' failed':s.phase==='won'?' won':'');renderControls();}
function renderControls(){if(!state)return;const me=state.players.find(p=>p.id===state.me),terminal=['won','lost','abandoned'].includes(state.phase),waiting=['lobby','between','retry'].includes(state.phase);$('ready').hidden=(!waiting&&!terminal)||(!terminal&&me?.excluded);$('ready').disabled=!connected||busy;$('ready').classList.toggle('is-ready',!!me?.ready&&!terminal);$('ready').innerHTML=terminal?'Volver al inicio ↗':me?.ready?'Estoy listo ✓':'Estoy listo <span>✓</span>';$('ready').setAttribute('aria-pressed',!!me?.ready);document.querySelectorAll('[data-card]').forEach(b=>b.disabled=!connected||playingCard||state.phase!=='playing');}
function animateEvent(e){sound(e.type);if(e.type==='card'){const c=$('table-card');c.classList.remove('deal');void c.offsetWidth;c.classList.add('deal')}if(['mistake','lost'].includes(e.type)){const a=$('arena');a.classList.remove('mistake');void a.offsetWidth;a.classList.add('mistake');if(navigator.vibrate)navigator.vibrate([70,50,70])}else $('arena').classList.remove('mistake');if(['success','won'].includes(e.type)){const a=$('arena');a.classList.add('success');for(let i=0;i<30;i++){const bit=document.createElement('i');bit.className='confetti';bit.style.cssText=`--left:${Math.random()*100}%;--color:${Math.random()*160};--delay:${Math.random()*.7}s`;a.append(bit);setTimeout(()=>bit.remove(),3500)}}else $('arena').classList.remove('success');if(['disconnect','reconnect','leave'].includes(e.type))toast(e.text)}
let lastCount=null;
function updateClock(){if(!state)return;const now=Date.now()+clockOffset;const remaining=state.deadline?Math.max(0,Math.ceil((state.deadline-now)/1000)):null;$('timer').textContent=remaining===null?'—':`${Math.floor(remaining/60)}:${String(remaining%60).padStart(2,'0')}`;$('timer').classList.toggle('urgent',remaining!==null&&remaining<=30);const count=state.phase==='countdown'?Math.max(1,Math.ceil((state.countdownAt-now)/1000)):null;$('countdown').hidden=count===null;if(count!==null&&count!==lastCount){$('countdown').textContent=count;$('countdown').classList.remove('pulse');void $('countdown').offsetWidth;$('countdown').classList.add('pulse');sound('countdown')}lastCount=count;}
setInterval(updateClock,150);
async function openStream(){const mine=++generation;streamController?.abort();while(session&&mine===generation){streamController=new AbortController();try{const response=await fetch(server+'/events',{headers:{Authorization:'Bearer '+session.token,'X-Room-Code':session.code},signal:streamController.signal});if(!response.ok){const data=await response.json();clearSession();toast(data.error||'La sala ya no está disponible.');return}setConnection(true);const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='';while(mine===generation){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});let at;while((at=buffer.indexOf('\n\n'))!==-1){const frame=buffer.slice(0,at);buffer=buffer.slice(at+2);if(frame.startsWith('event: expired')){clearSession();toast('La sala ha caducado o ya no estás en ella.');return}if(frame.startsWith('data: '))apply(JSON.parse(frame.slice(6)));}}}catch(e){if(e.name==='AbortError')return}if(mine!==generation)return;setConnection(false);await new Promise(resolve=>setTimeout(resolve,1800));}}
setInterval(async()=>{if(!session||!connected)return;try{const r=await api({action:'ping'});if(session)apply(r.state)}catch{setConnection(false);openStream()}},5000);
$('hand').onclick=async e=>{const b=e.target.closest('[data-card]');if(!b||playingCard||!connected)return;playingCard=true;renderControls();try{const r=await api({action:'play',card:Number(b.dataset.card),revision:state.revision});apply(r.state)}catch(e){toast(e.message)}finally{playingCard=false;renderControls()}};
$('ready').onclick=async()=>{if(['won','lost','abandoned'].includes(state.phase)){await leave();return}if(busy)return;busy=true;renderControls();try{sound('ready');const r=await api({action:'ready'});apply(r.state)}catch(e){toast(e.message)}finally{busy=false;renderControls()}};
function clearSession(){generation++;streamController?.abort();session=null;state=null;eventId=-1;saveSession();setConnection(false);$('home').hidden=false;$('room').hidden=true;history.replaceState(null,'',location.pathname);}
async function leave(){try{await api({action:'leave'})}catch{}clearSession();$('leave-dialog').close();}
$('leave').onclick=()=>$('leave-dialog').showModal();$('cancel-leave').onclick=()=>$('leave-dialog').close();$('confirm-leave').onclick=leave;
async function copy(text){try{await navigator.clipboard.writeText(text);toast('Copiado. Compártelo con tu equipo.')}catch{const t=document.createElement('textarea');t.value=text;document.body.append(t);t.select();const ok=document.execCommand('copy');t.remove();toast(ok?'Copiado.':`Copia este texto: ${text}`)}}
$('copy-code').onclick=()=>copy(state.code);$('copy-link').onclick=()=>{const url=new URL(location.href);url.search='';url.searchParams.set('sala',state.code);copy(url.href)};
$('save-server').onclick=()=>{try{const url=new URL($('server-url').value.trim());if(url.protocol!=='https:'&&!['localhost','127.0.0.1'].includes(url.hostname))throw Error();server=url.origin;store.set('synchrony-server',server);toast('Conexión guardada. Ya puedes entrar.')}catch{toast('Introduce una dirección HTTPS válida de Render.')}};
$('help').onclick=()=>$('help-dialog').showModal();document.querySelectorAll('.dialog-close,.dialog-close-button').forEach(b=>b.onclick=()=>$('help-dialog').close());
function soundLabel(){$('sound-label').textContent=soundOn?' ON':' OFF';$('sound').setAttribute('aria-label',soundOn?'Desactivar sonido':'Activar sonido')}
$('sound').onclick=()=>{soundOn=!soundOn;store.set('synchrony-sound',soundOn);soundLabel();sound('card')};soundLabel();$('name').value=store.get('synchrony-name')||'';$('server-url').value=server;
const invite=new URLSearchParams(location.search).get('sala');if(invite){tab('join');$('code').value=invite;}
if(session){server=session.server||server;$('home').hidden=true;$('room').hidden=false;$('status-title').textContent='Recuperando tu conexión…';$('ready').disabled=true;setConnection(false);openStream();}
window.addEventListener('offline',()=>{streamController?.abort();setConnection(false)});window.addEventListener('online',()=>{if(session)openStream()});
