const {test}=require('node:test');
const assert=require('node:assert/strict');
const {Game}=require('../game');
function setup(players=2,deck=100){let now=1000;const g=new Game({now:()=>now});const r=g.create({players,deck});const people=Array.from({length:players},(_,i)=>g.join(r,'Jugador '+i));return {g,r,people,advance(ms){now+=ms;for(const p of people)if(p.online)p.lastSeen=now;g.tick()}}}
function begin(t){for(const p of t.g.active(t.r))t.g.ready(t.r,p);t.advance(5000)}
test('código sensible a mayúsculas, sin filtrar manos ni tokens',()=>{const t=setup();assert.match(t.r.code,/^[A-Za-z0-9]{6}$/);begin(t);const v=t.g.view(t.r,t.people[0]);assert.equal(v.hand.length,1);assert.ok(v.players.every(x=>!('hand'in x)&&!('token'in x)));assert.ok(t.people[0].hand[0]!==t.people[1].hand[0]);});
test('todos listos y cuenta atrás de cinco segundos; la espera no gasta ronda',()=>{const t=setup();t.g.ready(t.r,t.people[0]);t.advance(20000);assert.equal(t.r.phase,'lobby');assert.equal(t.r.deadline,null);t.g.ready(t.r,t.people[1]);t.advance(4999);assert.equal(t.r.phase,'countdown');t.advance(1);assert.equal(t.r.phase,'playing');assert.equal(t.r.deadline,526000);});
test('error resta una vida, limpia manos y repite la misma ronda',()=>{const t=setup();begin(t);t.people[0].hand=[10];t.people[1].hand=[20];t.g.play(t.r,t.people[1],20,t.r.revision);assert.equal(t.r.lives,4);assert.equal(t.r.phase,'retry');assert.equal(t.r.round,1);assert.deepEqual(t.people[0].hand,[]);begin(t);assert.equal(t.r.round,1);assert.equal(t.r.lives,4);});
test('orden correcto avanza una ronda y reparte una carta adicional',()=>{const t=setup();begin(t);t.people[0].hand=[10];t.people[1].hand=[20];t.g.play(t.r,t.people[0],10,t.r.revision);t.g.play(t.r,t.people[1],20,t.r.revision);assert.equal(t.r.phase,'between');assert.equal(t.r.round,2);begin(t);assert.ok(t.people.every(p=>p.hand.length===2));});
test('cinco fallos terminan la partida',()=>{const t=setup();for(let i=0;i<5;i++){begin(t);t.people[0].hand=[1];t.people[1].hand=[2];t.g.play(t.r,t.people[1],2,t.r.revision)}assert.equal(t.r.phase,'lost');assert.equal(t.r.lives,0);assert.throws(()=>t.g.ready(t.r,t.people[0]));});
test('timeout se reinicia con la ronda y no corre entre rondas',()=>{const t=setup();begin(t);t.advance(500000);assert.equal(t.r.phase,'retry');assert.equal(t.r.lives,4);t.advance(10000);assert.equal(t.r.lives,4);begin(t);assert.equal(t.r.deadline,1021000);});
test('reconectar antes de 30 s conserva cartas y después solo permite observar',()=>{const t=setup();begin(t);const p=t.people[0],hand=[...p.hand];t.g.disconnect(t.r,p);t.advance(29999);t.g.connect(t.r,p);assert.deepEqual(p.hand,hand);t.g.disconnect(t.r,p);t.advance(30000);assert.equal(p.excluded,true);assert.equal(p.hand.length,0);t.g.connect(t.r,p);assert.equal(p.excluded,true);assert.throws(()=>t.g.play(t.r,p,hand[0],t.r.revision));});
test('una desconexión cancela la cuenta atrás',()=>{const t=setup();t.people.forEach(p=>t.g.ready(t.r,p));assert.equal(t.r.phase,'countdown');t.g.disconnect(t.r,t.people[0]);assert.equal(t.r.phase,'lobby');assert.ok(t.people.every(p=>!p.ready));});
test('900 s sin interacción eliminan la sala aunque siga conectada',()=>{const t=setup();t.advance(899999);assert.ok(t.g.rooms.has(t.r.code));t.advance(1);assert.equal(t.g.rooms.size,0);});
test('victoria al completar al menos el 79 %; nunca por cartas retiradas',()=>{const t=setup(2,100);t.r.round=40;begin(t);assert.equal(t.r.dealt,80);const plays=t.people.flatMap(p=>p.hand.map(n=>({p,n}))).sort((a,b)=>a.n-b.n);for(const {p,n} of plays)t.g.play(t.r,p,n,t.r.revision);assert.equal(t.r.phase,'won');const u=setup(2,100);u.r.round=40;begin(u);u.g.remove(u.r,u.people[1]);for(const n of [...u.people[0].hand])u.g.play(u.r,u.people[0],n,u.r.revision);assert.equal(u.r.phase,'between');});
test('privadas admiten más de 8 jugadores y más de 100 cartas',()=>{const t=setup(12,150);begin(t);assert.equal(t.r.dealt,12);assert.ok(t.people.every(p=>p.hand.length===1));assert.throws(()=>t.g.create({players:9,deck:100,public:true}));});
test('última ronda parcial respeta el tamaño de la baraja',()=>{const t=setup(60,100);t.r.round=2;begin(t);assert.equal(t.r.dealt,100);assert.equal(new Set(t.people.flatMap(p=>p.hand)).size,100);});
test('rechaza cartas ajenas y solicitudes repetidas con revisión antigua',()=>{const t=setup();begin(t);t.people[0].hand=[1];t.people[1].hand=[2];assert.throws(()=>t.g.play(t.r,t.people[0],2,t.r.revision));const rev=t.r.revision;t.g.play(t.r,t.people[0],1,rev);assert.throws(()=>t.g.play(t.r,t.people[1],2,rev));assert.equal(t.r.lives,5);});
